// 服务器返回的数据
var resultList = [
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":678,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":78,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":69,
        "goodRate":99,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":100,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":84,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":978,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6,
        "goodRate":74,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":94,
    }
    ,
    {
        "name":"Matebook X Pro Ultra典藏版",
        "promotionInfo":"预定立减300|12期免息",
        "promoLabels":[
            "分期免息",
            "赠送积分",
        ],
        "now":"13999",
        "discount":"14999",
        "rateCount":6978,
        "goodRate":94,
    }
]